from _typeshed import Incomplete
from pathlib import Path
from typing import Any

class DataUtil:
    def r_txt(self, path: str | Path) -> str: ...
    def r_csv(self, path: str | Path, read_encoding: str = 'utf-8') -> list[Any]: ...
    def r_tsv(self, path: str | Path) -> list[Any]: ...
    def r_json(self, json_path: str | Path) -> dict[Any, Any]: ...
    def r_pickle(self, pickle_path: str | Path) -> dict[Any, Any] | list[Any]: ...
    def r_auto(self, path: str | Path) -> dict[Any, Any] | list[Any]: ...
    def w_txt(self, txt: str, filename: str | Path | None = None) -> None: ...
    def w_log(self, content: str, filename: str | Path | None = None) -> None: ...
    def w_list(self, content_list: list[Any], filename: str | Path | None = None) -> None: ...
    def w_list_lf(self, content_list: list[Any], filename: str | Path | None = None) -> None: ...
    def w_csv(self, content_list: list[Any], filename: str | Path | None = None, write_encoding: str = 'utf-8') -> None: ...
    def w_csv_lf(self, content_list: list[Any], filename: str | Path | None = None, write_encoding: str = 'utf-8') -> None: ...
    def w_tsv(self, content_list: list[Any], filename: str | Path | None = None) -> None: ...
    def w_tsv_lf(self, content_list: list[Any], filename: str | Path | None = None) -> None: ...
    def w_dict(self, dic: dict[Any, Any], filename: str | Path | None = None) -> None: ...
    def w_json(self, dic_or_list: dict[Any, Any] | list[Any], filename: str | Path | None = None) -> None: ...
    def w_pickle(self, dic: dict[Any, Any], filename: str | Path | None = None) -> None: ...
    def w_auto(self, any_data: dict[Any, Any] | list[Any] | str | None, filename: str | Path | None = None, isNullable: bool = False) -> None: ...
    def str_to_list(self, raw_str: str, isSideTrim: bool = True) -> list[Any]: ...
    @property
    def yyyymmdd(self) -> str: ...
    @property
    def now(self) -> str: ...

du: Incomplete
